name: Beta Publish

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop

jobs:
  info:
    uses: ./.github/workflows/shared-workflows-info.yml

  publish-beta:
    needs: [info]
    if: needs.info.outputs.beta == 'true' && needs.info.outputs.skip-publish != 'true'
    uses: ./.github/workflows/shared-workflows-build.yml
    with: 
      version: ${{ needs.info.outputs.version }}