name: Docs

on:
  push:
    branches:
      - master

concurrency: 
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml
    with:
      skip-docs: true

  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v3
      - name: Prepare Env
        run: yarn install
      - name: Build Docs
        run: yarn build:docs
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: src/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
