name: Publish

on:
  push:
    branches:
      - master

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml
    with:
      skip-docs: true

  info:
    uses: ./.github/workflows/shared-workflows-info.yml

  publish:
    needs: [info, lint]
    if: needs.info.outputs.beta == 'false' && needs.info.outputs.skip-publish != 'true'
    uses: ./.github/workflows/shared-workflows-publish.yml
    with: 
      version: ${{ needs.info.outputs.version }}