name: Publish

on:
  push:
    branches:
      - master

jobs:
  info:
    uses: ./.github/workflows/shared-workflows-info.yml

  publish:
    needs: [info]
    if: needs.info.outputs.beta == 'false' && needs.info.outputs.skip-publish != 'true'
    uses: ./.github/workflows/shared-workflows-build.yml
    with: 
      version: ${{ needs.info.outputs.version }}