name: Publish

on:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml

  info:
    uses: ./.github/workflows/shared-workflows-info.yml

  publish:
    needs: [info, lint]
    if: needs.info.outputs.beta == 'false' && needs.info.outputs.skip-publish != 'true'
    uses: ./.github/workflows/shared-workflows-publish.yml
    with: 
      version: ${{ needs.info.outputs.version }}