name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml

  discord:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_PR_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_PR_WEBHOOK_TOKEN }}
          args: "PullRequest Criada/Atualizada: #${{ github.event.number }} \nhttps://github.com/eduzz/houston/pull/${{ github.event.number }}"
