name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-lint-build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v3
      - name: Yarn
        run: npm i -g yarn
      - name: Prepare Env
        run: yarn install
      - name: Linter
        run: yarn lint
      - name: Build Packages
        run: yarn build
      - name: Build Docs
        run: yarn build:docs
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_PR_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_PR_WEBHOOK_TOKEN }}
          args: "PullRequest Criada/Atualizada: #${{ github.event.number }} \nhttps://github.com/eduzz/houston/pull/${{ github.event.number }}"
